### ISSUE TITLE
grunt failed

### ISSUE THREAD

**Issue by physiii** [aaharu/gifken#1]
Running "typescript:build" (typescript) task
>> src/gifken.ts(118,28): error TS2304: Cannot find name 'DataView'.
>> src/gifken.ts(210,30): error TS2304: Cannot find name 'DataView'.
>> src/gifken.ts(248,34): error TS2304: Cannot find name 'DataView'.
>> src/gifken.ts(272,33): error TS2304: Cannot find name 'DataView'.
>> src/gifken.ts(541,41): error TS2304: Cannot find name 'DataView'.
>> src/gifken.ts(564,40): error TS2304: Cannot find name 'DataView'.
>> src/gifken.ts(614,49): error TS2304: Cannot find name 'DataView'.
>> src/gifken.ts(655,60): error TS2304: Cannot find name 'DataView'.
>> src/gifken.ts(680,56): error TS2304: Cannot find name 'DataView'.
>> src/gifken.ts(693,67): error TS2304: Cannot find name 'DataView'.
>> src/gifken.ts(701,58): error TS2304: Cannot find name 'DataView'.
Warning: Task "typescript:build" failed. Use --force to continue.

Aborted due to warnings.

**Comment by aaharu** [comment]
thx!
