### ISSUE TITLE
GifPresenter class is not exported

### ISSUE THREAD

**Issue by GMartigny** [aaharu/gifken#15]
Hi,

The `GifPresenter` class is not part of the gifken exports. According to the documentation, I should be be doing:

```js
	newimg.src = gifken.GifPresenter.writeToDataUrl(newgif.writeToArrayBuffer());
```

**Comment by aaharu** [comment]
Hi, thanks for this report.

`GifPresenter` class is included only `gifken.umd.js`, because it uses [Blob](https://developer.mozilla.org/ja/docs/Web/API/Blob) and [btoa](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/btoa).
I'll fix the documentation 😃

**Comment by GMartigny** [comment]
Ok, thanks.
With the advent of ESM as the common import format you might want to consider adding it to your ESM build. Now, you'll have issue with Node.js, I know we all wonder how to work this out ^^.
